
/**
 * Serializes the specified value using a custom JSON format that supports
 * object references (circular or otherwise), custom serialization callbacks
 * and concrete class reconstitution.
 *
 * @param {any} value the value to serialize.
 * @return {string} the serialized value.
 */
export function serialize(value) {
	return (new Serializer()).serialize(value);
}

/**
 *
 * @param {string} data the serialized JSON data to deserialize.
 * @returns {any} the deserialized object.
 */
export function deserialize(data) {
	return (new Deserializer()).deserialize(data);
}

/**
 * @typedef {{readonly [key:string]: any}} SerializedData
 */

/**
 * Signature for a factory function to invoke to create new instances of a class
 * during deserialization.
 *
 * Since this function is responsible for creating the object, it is not possible to
 * deserialize child properties with a circular reference back to the object being
 * created.  Attempts to do so will result in an exception.
 *
 * @callback FactoryCallback
 * @param {ClassEntry} entry the ClassEntry for the class.
 * @param {SerializedData} data the serialized data associated with the object.  May be used for
 * 		extracting constructor arguments, etc., but will not support circular
 * 		references back to the object being constructed.
 * @param {Deserializer} deserializer the deserializer to use to deserialize any necessary
 * 		values from the `data`.
 * @return {any}
 */

/**
 * Signature for custom class serialization methods.
 *
 * @callback SerializeCallback
 * @param {any} obj the object being serialized.
 * @param {Serializer} serializer the Serializer instance to use for serializing data.
 * @return {void}
 */

/**
 * Signature for custom class deserialization methods.
 *
 * @callback DeserializeCallback
 * @param {any} obj the object being deserialized.
 * @param {SerializedData} data the data associated with the object as generated by the class'
 * 				serialization callback.
 * @param {Deserializer} deserializer the Deserializer instance to use for deserializing data.
 * @return {void}
 */

/**
 * Class entry properties for the ClassRegistry.
 * @interface
 */
export class ClassEntry {
	/**
	 * Name of the class this entry is for.
	 * @readonly
	 * @type {string}
	 */
	name;

	/**
	 * Class' constructor function.
	 *
	 * This function will be used to identify members of the class for serialization,
	 * as well as to construct new instances during deserialization if a factory function
	 * isn't defined.
	 *
	 * @readonly
	 * @type {Function}
	 */
	constructorFunction;

	/**
	 * Factory method to invoke to create new instances of this class during deserialization.
	 *
	 * If not defined, instances will be created using the constructor function.
	 *
	 * Since this function is responsible for creating the object, it is not possible to
	 * deserialize child properties with a circular reference back to the object being
	 * created.  Attempts to do so will result in an exception.
	 *
	 * @readonly
	 * @type {FactoryCallback?}
	 */
	factory;

	/**
	 * Serialization callback to invoke to serialize instances of this class.
	 *
	 * @readonly
	 * @type {SerializeCallback?}
	 */
	serializer;

	/**
	 * Deserialization callback to invoke to deserialize instances of this class.
	 * This function is invoked _after_ the instance is created, so circular references
	 * are supported.
	 *
	 * @readonly
	 * @type {DeserializeCallback?}
	 */
	deserializer;
}

/**
 * Registry of class names and constructor functions to use during serialization
 * and deserialization.
 *
 * When serializing, entries are retrieved based on an object's constructor.  Only objects
 * that match a registered constructor can be serialized.
 *
 * When deserializing, entries are retrieved based on the target class name.  Only classes
 * that have been registered can be successfully deserialized.
 */
export class ClassRegistry {

	/**
	 * @readonly
	 * @type {Map<string, ClassEntry>}
	 */
	static #registryByName = new Map();

	/**
	 * @readonly
	 * @type {Map<Function, ClassEntry>}
	 */
	static #registryByConstructor = new Map();

	/**
	 * Registers a class name/conssrtuctor and associated callbacks.
	 *
	 * @template T
	 *
	 * @param {string} name the class name.
	 * @param {Function} constructorFunction the class constructor function to associate with the name.
	 * @param {((obj: T, serializer: Serializer) => void)?} serializer serialization function to invoke
	 *          for objects with the specified constructor.  If this argument is omitted, the
	 *          `constructorFunction` will be examined for an associated `serialize` method instead.
	 *          If neither is set, the default "bare" object serialization will be used.
	 * @param {((obj: T, data: SerializedData, deserializer: Deserializer) => void)?} deserializer
	 *          deserialization function to invoke when objects with the specified class name are
	 *          encountered.  If this argument is omitted, the `constructorFunction` will be examined
	 *          for an associated `deserialize` method instead.  If neither is set, the default "bare"
	 *          object deserialization will be used.
	 * @param {((entry: ClassEntry, data: SerializedData, deserializer: Deserializer) => T)?} factory
	 *        factory function to use for constructing new instances instead of the `constructorFunction`.
	 *        If this argument is omitted, the `constructorFunction` will be examined for an associated
	 *        `factory` method instead.  If neither is set, new instances of this class will be
	 *        created by invoking the `constructorFunction` via the `new` operator.
	 *
	 * @throws Error if the specified name or constructor function are already registered.
	 *
	 * @see [[ClassEntry]]
	 */
	static registerClass(name, constructorFunction, serializer, deserializer, factory) {
		if (this.#registryByName.has(name))
			throw new Error("Class name '" + name + "' already registered");

		let prevName = this.#registryByConstructor.get(constructorFunction);
		if (prevName != null) {
			throw new Error("Class constructor already registered under name '" + prevName.name + "'");
		}

		if (serializer == null) {
			serializer = constructorFunction.serialize;
		}

		if (deserializer == null) {
			deserializer = constructorFunction.deserialize;
		}

		if (factory == null) {
			factory = constructorFunction.factory
		}

		/** @type ClassEntry */
		const entry = {
			name: name,
			constructorFunction: constructorFunction,
			serializer: serializer,
			deserializer: deserializer,
			factory: factory
		};

		this.#registryByName.set(name, entry);
		this.#registryByConstructor.set(constructorFunction, entry);
	}

	/**
	 * Retrieves a registry entry by class name or constructor.
	 *
	 * @param {string|Function} nameOrConstructor The class name or constructor function to
	 *        retrieve the entry for.
	 *
	 * @return {ClassEntry|undefined} The `ClassEntry` matching the name/constructor, or undefined
	 *         if not found.
	 */
	static getClassEntry(nameOrConstructor) {
		if (nameOrConstructor instanceof Function) {
			return this.#registryByConstructor.get(nameOrConstructor);
		} else {
			return this.#registryByName.get(nameOrConstructor);
		}
	}
}

/**
 * Class for serializing values to a custom JSON format that supports
 * object references (circular or otherwise), custom serialization callbacks
 * and concrete class reconstitution.
 *
 * The serialized data will be valid JSON, but some values will be serialized using
 * a custom format as follows:
 *
 * - Symbols for which Symbol.keyFor() returns a value:
 *   `{"$type":["Symbol", "some symbol key"]}`
 *
 * - Objects that have not been serialized earlier in the output which were created using
 *   the Object constructor or are instances of a registered custom class:
 *   `{"$type": ["SomeClassName", 1234], ...data props}`
 *   Where the reference number (1234 in the above example) will be unique for each object
 *   in the output.  The associated data properties will be encoded based on the serializer
 *   function registered for the class.
 *
 * - Objects which have been serialized earlier in the output:
 *   `{"$type": 1234}`
 *   Where the reference number (1234 in the above example) will be unique for each object
 *   in the output.
 *
 * - undefined will be serialized as:
 *   `{"$type":"undefined"}`
 *
 * @see [[Deserializer]]
 */
export class Serializer {

	// TODO: Support serialization to a stream or file?

	/**
	 * Name of the property that holds the object type and reference id.
	 * @readonly
	 * @type {string}
	 */
	#typeKeyName;

	/**
	 * @readonly
	 * @type {string}
	 */
	#typeKeyNameJson;

	/**
	 * Property path from the root to the current value.
	 * Updated for each object property or array element
	 * @readonly
	 * @type {string[]}
	 */
	#path = [];

	/**
	 * Flag indicating whether additional data may be serialized or not.
	 * @type {boolean}
	 */
	#closed = false;

	/**
	 * The object currently being serialized, or undefined if not serializing an object.
	 * Used for determining if an object attempts to serialize itself, and whether calls
	 * to writeProp are valid.
	 * @type {any}
	 */
	#currentObject;

	/**
	 * Serialized fragments generated up to the current point in the process.
	 * @readonly
	 * @type {string[]}
	 */
	#buffer = [];

	/**
	 * The number of objects serialized so far.
	 * @type {number}
	 */
	#referenceCount = 0;

	/**
	 * Map of {object -> reference id} for all objects serialized so far.
	 * Used to support circular references and ensure instance identities are preserved
	 * in the serialized data by writing a reference instead of infinitely recursing or
	 * re-serializing when an object is encountered multiple times.
	 * @readonly
	 * @type {Map<Object, number>}
	 */
	#references = new Map();

	/**
	 * Constructs a new serializer which uses the specified type key name when serializing
	 * objects.
	 *
	 * @param {string} typeKeyName the object property name to use for storing an object's
	 *        type and reference information.  Defaults to '$type'.
	 */
	constructor(typeKeyName = "$type") {
		this.#typeKeyName = typeKeyName;
		this.#typeKeyNameJson = JSON.stringify(typeKeyName);
	}

	/**
	 * The object property name to use for storing an object's type and reference information.
	 */
	get typeKeyName() {
		return this.#typeKeyName;
	}

	/**
	 * Serialize the specified value and return the result.
	 *
	 * @param {any} value the value to serialize.
	 *
	 * @return {string} the serialized string.
	 */
	serialize(value) {
		this.write(value);
		return this.getString();
	}

	/**
	 * Retrieve the serialized string and clear the internal buffer.
	 *
	 * This would usually be called at the end of an incremental serialization.
	 *
	 * @return {string} the serialized string up to the current point in the process.
	 * @throws Error if the serializer's closed flag is not set.
	 */
	getString() {
		this.#assertClosed();
		return this.#buffer.join("");
	}

	/**
	 * Appends the specified strings to the end of the serialization buffer.
	 * @param {string[]} pieces the strings to append.
	 */
	#append(...pieces) {
		this.#buffer.push(...pieces);
	}

	/**
	 * Ensures that the closed flag is set, and throws an Error if not.
	 */
	#assertClosed() {
		if (!this.#closed) {
			throw new Error("Serialization incomplete at '" + this.#path.join(".") + "'");
		}
	}

	/**
	 * Ensures that writing new values is possible.
	 *
	 * Performs the following checks:
	 * - Checks that the closed flag is NOT set.
	 * - Requires there is no current object being written.
	 *
	 * @throws Error if any of the above checks fail.
	 */
	#assertCanWrite() {
		if (this.#closed) {
			throw new Error("Current state doesn't permit writing value at '" + this.#path.join(".") + "'");
		}

		if (this.#currentObject != null) {
			throw new Error("Cannot write value without property name, call writeProp instead");
		}
	}

	/**
	 * Sets the closed flag if the current nesting level is 0.
	 */
	#closeIfTopLevel() {
		if (this.#path.length == 0) {
			this.#closed = true;
		}
	}

	/**
	 * Appends all object properties from the specified object to the serialized data
	 * for the current object.
	 *
	 * May only be called from within a serialization function for a registered class.
	 *
	 * @overload
	 *
	 * @param {any} props an object containing the properties to write.
	 *
	 * @throws Error if not currently executing a serialization function, or if
	 *		serialization fails.
	 */
	/**
	 * Appends an object property to the serialized data for the current object.
	 *
	 * May only be called from within a serialization function for a registered class.
	 *
	 * @overload
	 *
	 * @param {string} name the name of the property to write.
	 * @param {any} value the value for the property.
	 *
	 * @throws Error if not currently executing a serialization function, or if
	 *		serialization fails.
	 */
	/**
	 * @overload
	 * @param {string|Object} nameOrProps
	 * @param {any} value
	 */
	writeProp(nameOrProps, value) {
		if (this.#currentObject == null) {
			throw new Error("writeProp may only be invoked from inside a custom serialization callback");
		}

		let prevCurrent = this.#currentObject;
		this.#currentObject = undefined;

		const n = this.#path.length;

		const write = (name, value) => {
			this.#path[n] = name;
			this.#append(",");
			this.#append(JSON.stringify(name), ':');
			this.write(value);
		}

		if (typeof nameOrProps === "string") {
			write(nameOrProps, value);
		} else {
			const obj = nameOrProps;
			for (let name in obj) if (obj.hasOwnProperty(name)) {
				write(name, obj[name]);
			}
		}

		this.#path.length = n;

		this.#currentObject = prevCurrent;
	}

	/**
	 * Writes the specified object in a "bare" format.
	 *
	 * @param {any} obj the object being serialized.
	 * @param {Serializer} serializer the Serializer instance.
	 */
	#defaultSerializerCallback(obj, serializer) {
		for (let name in obj) if (obj.hasOwnProperty(name)) {
			serializer.writeProp(name, obj[name]);
		}
	}

	/**
	 * Serializes the specified object.
	 *
	 * @param {Object} obj the object to serialize.
	 *
	 * @throws Error if the serializer's closed flag is set, the class name could not
	 * 		be determined (possibly unregistered constructor), the class' serialize
	 *		function did not write anything, or serialization of a child property failed.
	 */
	writeObject(obj) {
		if ((obj == null) || (obj instanceof String) || (obj instanceof Boolean) || (obj instanceof Number)) {
			this.writePrimitive(obj.valueOf());
			return;
		}

		this.#assertCanWrite();

		let refId = this.#references.get(obj);
		if (refId != null) {
			this.#append('{', this.#typeKeyNameJson, ':', String(refId), '}');
		} else {
			refId = this.#referenceCount++;
			this.#references.set(obj, refId);

			const classEntry = ClassRegistry.getClassEntry(obj.constructor);
			if (classEntry == null) {
				throw new Error("Unable to determine object class name at '" + this.#path.join(".") + "'");
			}

			this.#append(
				'{', this.#typeKeyNameJson, ':[', JSON.stringify(classEntry.name), ',', JSON.stringify(refId), ']'
			);

			const serializer = classEntry.serializer;
			if (serializer == null) {
				serializer = this.#defaultSerializerCallback;
			}

			let prevCurrent = this.#currentObject;
			this.#currentObject = obj;

			serializer(obj, this);

			this.#currentObject = prevCurrent;

			this.#append("}");
		}

		this.#closeIfTopLevel();
	}

	/**
	 * Serializes the specified array.
	 *
	 * @param {ReadonlyArray<any>} value the array to serialize.
	 *
	 * @throws Error if the serializer's closed flag is set, or serialization of
	 * 		an item in the array failed.
	 */
	writeArray(value) {
		this.#assertCanWrite();

		this.#append("[");

		const n = this.#path.length;
		let index = 0;
		for (let item of value) {
			if (index > 0) {
				this.#append(",");
			}

			this.#path[n] = String(index++);
			this.write(item);
		}
		this.#path.length = n;

		this.#append("]");

		this.#closeIfTopLevel();
	}

	/**
	 * Serializes the specified primitive (string,number,boolean,null,undefined) value.
	 * @param {String|number|boolean|null|undefined} value the primitive value to serialize.
	 */
	writePrimitive(value) {
		this.#assertCanWrite();

		if (value === undefined) {
			// Special value written to preserve undefined
			this.#append('{"$type":"undefined"}');
		} else {
			this.#append(JSON.stringify(value));
		}

		this.#closeIfTopLevel();
	}

	/**
	 * Serializes the specified global symbol.
	 *
	 * @param {symbol} symbol the symbol to serialize.
	 *
	 * @throws Error if the symbol key could not be retrieved (e.g. not a global symbol
	 *			created with Symbol.for).
	 */
	writeSymbol(symbol) {
		this.#assertCanWrite();

		const key = Symbol.keyFor(symbol);
		if (key == null) {
			throw new Error("Unable to determine key for symbol at '" + this.#path.join(".") + "'");
		}

		this.#append('{', this.#typeKeyNameJson, ':["Symbol",', JSON.stringify(key), ']}');

		this.#closeIfTopLevel();
	}

	/**
	 * Serializes the specified value.
	 *
	 * @param {any} value the value to serialize.
	 *
	 * @throws Error if the value could not be serialized successfully.
	 */
	write(value) {
		let t = typeof value;
		switch (t) {
		case "object":
			if (Array.isArray(value)) {
				this.writeArray(value);
			} else {
				this.writeObject(value);
			}
			break;

		case "function": // Callbacks created by Parse.action/Parse.listener/etc can be serialized
			this.writeObject(value);
			break;

		case "string":
		case "number":
		case "boolean":
		case "undefined":
			this.writePrimitive(value);
			break;

		case "symbol":
			this.writeSymbol(value);
			break;

		default:
			throw new Error("Cannot serialize " + t + " value at '" + this.#path.join(".") + "'");
		}
	}
}

/**
 * Deserializes data serialized by the Serializer class.
 * @see [[Serializer]]
 */
export class Deserializer {
	/**
	 * Name of the property that holds the object type and reference id.
	 * @readonly
	 * @type {string}
	 */
	#typeKeyName;

	/**
	 * Property path from root to the current value
	 * @readonly
	 * @type {string[]}
	 */
	#path = [];

	/**
	 * Map of {reference id -> object} for all objects deserialized so far.
	 * Used for resolving references encountered in the serialized data to their
	 * respective object instances.
	 * @readonly
	 * @type {Map<number, Object>}
	 */
	#references = new Map();

	/**
	 * The object currently being deserialized, or undefined if not deserializing an object.
	 * Used for determining if a custom deserialize function calls readObject with the
	 * data object passed to deserialize, which should invoke the default deserialization.
	 * @type {any}
	 */
	#currentObject;

	/**
	 *
	 * @param {string} typeKeyName
	 */
	constructor(typeKeyName = '$type') {
		this.#typeKeyName = typeKeyName;
	}

	get typeKeyName() {
		return this.#typeKeyName;
	}

	/**
	 * Deserializes a string into the object structure it represents.
	 * @param {string} data the string to deserialize.
	 */
	deserialize(data) {
		return this.read(JSON.parse(data));
	}

	#assertCanRead() {
		if (this.#currentObject != null) {
			throw new Error("Cannot read value without property name, call readProp instead");
		}
	}

	/**
	 * Recursively deserializes the items in the specified array.
	 * @param {ReadonlyArray<any>} value the array to process.
	 * @return {any[]} a new array containing the deserialized values.
	 */
	readArray(value) {
		this.#assertCanRead();

		const rv = [];
		const n = this.#path.length;
		for (let i = 0; i < value.length; ++i) {
			this.#path[n] = String(i);
			rv[i] = this.read(value[i]);
		}
		this.#path.length = n;
		return rv;
	}

	/**
	 * Reads all properties from a source object and returns a new object containing the
	 * deserialized property values.
	 *
	 * @abstract
	 *
	 * @param {SerializedData} sourceObj the serialized object to read the properties from.
	 *
	 * @return {Object} a new object containing the deserialized property data.
	 */
	readProp(sourceObj) {}

	/**
	 * Reads a property from a source object and returns the deserialized value.
	 *
	 * @abstract
	 *
	 * @param {SerializedData} sourceObj the serialized object to read the property from.
	 * @param {string} name the name of the property to read.
	 *
	 * @return {any} the deserialized property value.
	 */
	readProp(sourceObj, name) {}

	/**
	 * Reads all properties from a source object and writes the deserialized property values
	 * into a provided destination object.
	 *
	 * @abstract
	 *
	 * @param {SerializedData} sourceObj the serialized object to read the properties from.
	 * @param {Object} destObj the destination object to write the deserialized property values to.
	 *
	 * @return {Object} the destination object.
	 */
	readProp(sourceObj, destObj) {}

	/**
	 *
	 * @param {SerializedData} sourceObj
	 * @param {(string|Object)?} nameOrDest
	 * @returns
	 */
	readProp(sourceObj, nameOrDest) {
		if (this.#currentObject == null) {
			throw new Error("readProp may only be invoked from inside a custom deserialization callback");
		}

		const prevCurrent = this.#currentObject;
		this.#currentObject = undefined;

		const n = this.#path.length;
		const read = (name) => {
			this.#path[n] = name;
			return this.read(sourceObj[name]);
		}

		let rv;
		if (typeof nameOrDest === "string") {
			// Read a single property
			rv = read(nameOrDest);
		} else {
			if (nameOrDest == null)
				nameOrDest = {};

			// Read object
			rv = nameOrDest;
			for (let name in sourceObj) {
				if (sourceObj.hasOwnProperty(name) && (name != this.#typeKeyName)) {
					rv[name] = read(name);
				}
			}
		}

		this.#path.length = n;

		this.#currentObject = prevCurrent;
		return rv;
	}

	/**
	 * Default Object deserialize callback.
	 *
	 * Recursively deseralizes each property of the data object and assigns the result
	 * to the corresponding property of the target object.
	 *
	 * @param {Object} destObj the target object to apply deserialized values to.
	 * @param {SerializedData} data the serialized object data.
	 * @param {Deserializer} deserializer the deserializer to use for deserializing values.
	 */
	#defaultDeserializerCallback(destObj, data, deserializer) {
		deserializer.readProp(data, destObj);
	}

	/**
	 * Recursively deserializes the specified object.
	 * @param {any} obj the serialized object data to deserialize.
	 * @return {any} the deserialized object.
	 */
	readObject(obj) {
		this.#assertCanRead();

		if ((obj == null) || (obj instanceof String) || (obj instanceof Boolean) || (obj instanceof Number)) {
			return obj;
		}

		const data = obj;
		/** @type [string,number|string]|string|number|undefined */
		const $type = data[this.#typeKeyName];
		if ($type != null) {
			if (typeof $type === "string") {
				if ($type == "undefined") {
					return undefined;
				}

				throw new Error("Invalid " + this.#typeKeyName + " property value: "+ $type + " at " + this.#path.join(".") + "'");
			}

			if (typeof $type == "number") {
				let rv = this.#references.get($type);
				if (rv != null) {
					return rv;
				}

				throw new Error("Invalid object reference #" + $type +" at " + this.#path.join(".") + "'");
			}

			if (typeof $type[1] === "string") {
				return Symbol.for($type[1]);
			}

			const className = $type[0];
			const classEntry = ClassRegistry.getClassEntry(className);
			if (classEntry == null) {
				throw new Error("No registry entry for class '" + className + "' at " + this.#path.join(".") + "'");
			}

			const refId = $type[1];
			if (refId == null) {
				throw new Error("Missing object reference id at " + this.#path.join(".") + "'");
			}

			const prevCurrent = this.#currentObject;
			this.#currentObject = data;

			// Create new instance
			let rv;
			if (classEntry.factory) {
				rv = classEntry.factory.call(this, classEntry, data, this);
			} else {
				rv = new classEntry.constructorFunction();
			}

			// Register instance
			this.#references.set(refId, rv);

			// Deserialize object properties
			let deserializer = classEntry.deserializer;
			if (deserializer == null) {
				deserializer = this.#defaultDeserializerCallback;
			}

			deserializer.call(this, rv, data, this);

			this.#currentObject = prevCurrent;

			return rv;
		}

		throw new Error("Unable to deserialize object: Does not have '" + this.#typeKeyName + "' property.");
	}

	/**
	 * Recursively deserializes the specified value.
	 * @param {any} value the value to deserialize.
	 * @return {any} the deserialized value.
	 */
	read(value) {
		let t = typeof value;
		switch (t) {
		case "object":
			if (Array.isArray(value)) {
				return this.readArray(value);
			} else {
				return this.readObject(value);
			}

		case "string":
		case "number":
		case "boolean":
		case "undefined":
			this.#assertCanRead();
			return value;

		default:
			throw new Error("Cannot deserialize " + t + " value at '" + this.#path.join(".") + "'");
		}
	}

}

ClassRegistry.registerClass('Object', Object);

ClassRegistry.registerClass('Map', Map,
	(map, serializer) => {
		/** @type [any,any][] */
		let rv = [];

		for (let item of map.entries()) {
			rv.push(item);
		}

		serializer.writeProp("entries", rv);
	},
	(map, data, deserializer) => {
		for (let item of deserializer.readProp(data, "entries")) {
			map.set(
				deserializer.read(item[0]),
				deserializer.read(item[1])
			);
		}
	}
);

ClassRegistry.registerClass('Set', Set,
	(set, serializer) => {
		let rv = [];

		for (let item of set.values()) {
			rv.push(item);
		}

		serializer.writeProp("entries", rv);
	},
	(set, data, deserializer) => {
		for (let item of deserializer.readProp(data, "entries"))
			set.add(item);
	}
);
